---
NUM_CORES: 8

DATASET: practice_E_1
OUTPUT_SIZE:  1000000
KEY_SIZE: 12

DATA_PATH: data

MAXIMUM_MISMATCH_COUNT: 3
MINIMUM_NUMBER_OF_PIECES_TO_MATCH: 3
PAIRED_GAP_ESTIMATE_INTERVAL:
  - 135
  - 165
MAX_PAIRED_MISMATCH_COUNT: 3
MIN_COVERAGE_FOR_INCLUSION: 2
READ_SIZE: 50
